### ISSUE TITLE
Nested arrays aren't formatted correctly

### ISSUE THREAD

**Issue by c24w** [mysqljs/sqlstring#26]
>Nested arrays are turned into grouped lists (for bulk inserts), e.g. [['a', 'b'], ['c', 'd']] turns into ('a', 'b'), ('c', 'd')

However, this is the behaviour:
```
require('sqlstring').format('?', [ [12, 34], [56, 78] ])
// => '12, 34'
```

It works correctly when using `escape`:
```
require('sqlstring').escape([ [12, 34], [56, 78] ])
// => '(12, 34), (56, 78)'
```

**Comment by dougwilson** [comment]
So the issue is that the `format` function takes two arguments: first is the sting of SQL with `?` placeholders and the second is an array where each element corresponds to each `?`. You see, you called it as the following:
```js
require('sqlstring').format('?', [ [12, 34], [56, 78] ])
```

Where that deconstructs as:
```js
let arg1 = '?'
let arg2 = [ [12, 34], [56, 78] ]
require('sqlstring').format(arg1, arg2)
```

So the first `?` in your `arg1` will be the first element in the array `arg2`, which is `arg2[0]`, which is just `[12, 34]`. Really you wanted that to be the entire thing.

The correct call is the following:
```
require('sqlstring').format('?', [ [ [12, 34], [56, 78] ] ])
// => '(12, 34), (56, 78)'
```
