### ISSUE TITLE
Buffers should be converted .toSting() with the original Buffer.prototype.toString()

### ISSUE THREAD

**Issue by ChALkeR** [mysqljs/sqlstring#6]
```js
var x = Buffer.from('lol');
x.toString = () => "00\' OR '1' = '1";
SqlString.format("SELECT * FROM user WHERE user = ?", x);
```
results in
```sql
SELECT * FROM user WHERE user = X'00' OR '1' = '1'
```

This doesn't look like a security issue to me, because whomever allows user-supplied `.toString()` override has much bigger problems than a potential SQLi.

**Comment by dougwilson** [comment]
Yea, sounds like just a general formatting issue; ideally we should trust that if the Node.js core `Buffer.isBuffer` says `true`, we should trust that the object Node.js said was a buffer is adhering to the https://nodejs.org/api/buffer.html#buffer_buf_tostring_encoding_start_end in some way :)

I'm trying to thing of what a good way to address this is. I can think of the following possibilities:
1. Implement our own buffer to hex string function, reading the bytes ourselves. Seems less desirable, since the Node.js one is done in C++
2. Don't assume that `.toString('hex')` will be a hex string, and run that result itself through `SqlString.escape`. This would probably end up as a SQL syntax error, but not SQLi (the example above would end up as `SELECT * FROM user WHERE user = X'00\' OR \'1\' = \'1'`.
3. Run a regular expression across the `.toString('hex')` result and throw if it does not contain only hex characters.
